apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent
  namespace: qbittorrent
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: traefik-body-size-8m@kubernetescrd,traefik-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "qbittorrent.k8s.javydekoning.com"
      secretName: javydekoning-com-tls
  rules:
    - host: "qbittorrent.k8s.javydekoning.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: qbittorrent-web
                port:
                  number: 80
