apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: javydekoning-com-tls
  namespace: traefik
spec:
  secretName: javydekoning-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.javydekoning.com"
    - "*.k8s.javydekoning.com"
    - "*.lab.javydekoning.com"
