apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.1
    releaseName: traefik
    namespace: traefik
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - ns.yaml
  - certificate.yaml
