apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx-external

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.14.2
    releaseName: ingress-nginx
    namespace: ingress-nginx-external
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - ns.yaml
