apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik-external

helmCharts:
  - name: traefik
    repo: https://traefik.github.io/charts
    version: 39.0.0
    releaseName: traefik-external
    namespace: traefik-external
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - ns.yaml
  - certificate.yaml
