apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: n8n

helmCharts:
  - name: n8n
    repo: https://community-charts.github.io/helm-charts
    version: 1.16.4
    releaseName: n8n
    namespace: n8n
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - namespace.yaml
  - volume.yaml
  - external-secret.yaml
