main:
  count: 1
  editorBaseUrl: "https://n8n.k8s.javydekoning.com"

  persistence:
    enabled: true
    volumeName: "n8n-data"
    storageClass: "local-path"

timezone: "Europe/Amsterdam"

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: n8n.k8s.javydekoning.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: javydekoning-com-tls
      hosts:
        - n8n.k8s.javydekoning.com

serviceMonitor:
  enabled: true

existingEncryptionKeySecret: n8n-credentials
