model_list:
  - model_name: claude-opus-latest
    litellm_params:
      model: os.environ/CLAUDE_OPUS_LATEST_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  - model_name: claude-sonnet-latest
    litellm_params:
      model: os.environ/CLAUDE_SONNET_LATEST_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  - model_name: claude-haiku-latest
    litellm_params:
      model: os.environ/CLAUDE_HAIKU_LATEST_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY
  - model_name: amazon-nova-lite
    litellm_params:
      model: os.environ/NOVA_LITE_INF_ARN
      aws_region_name: eu-west-1
      aws_access_key_id: os.environ/AWS_ACCESS_KEY_ID
      aws_secret_access_key: os.environ/AWS_SECRET_ACCESS_KEY

mcp_servers:
  time:
    transport: "stdio"
    command: "uvx"
    args: ["mcp-server-time", "--local-timezone=Europe/Amsterdam"]
  litellm_docs:
    url: "https://gitmcp.io/BerriAI/litellm"
    transport: "sse"
    auth_type: "none"
  aws_knowledge_mcp:
    url: "https://knowledge-mcp.global.api.aws"
    transport: "http"
    description: "AWS Knowledge MCP Server"
    auth_type: "none"
  home_assistant:
    url: "http://home-assistant.smarthome.svc.cluster.local:8123/mcp_server/sse"
    transport: "sse"
    description: "Home Assistant MCP Server"
    auth_type: "bearer_token"
    auth_value: "os.environ/HASS_API_KEY"
  timenpx:
    transport: "stdio"
    command: "npx"
    args: ["-y", "@theo.foobar/mcp-time"]
    env:
      KARAKEEP_API_ADDR: "https://karakeep.lab.javydekoning.com"
      KARAKEEP_API_KEY: "os.environ/KARAKEEP_API_KEY"
