---
# Homepage configuration
# See https://fontawesome.com/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Homelab app dashboard"
subtitle: "Running on k3s!"
logo: "logo.png"
icon: fas fa-server" # Optional icon

header: true
footer: false
columns: auto
connectivityCheck: true

links:
  - name: "Github"
    icon: "fas fa-book"
    url: "https://github.com/javydekoning/homelab"

defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon &
# tagstyle are optional, section separation will not be displayed).
services:
  - name: "Media & Entertainment"
    icon: "fas fa-play"
    items:
      - name: "Jellyfin"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/jellyfin.svg"
        subtitle: "Media server"
        url: "https://jellyfin.k8s.javydekoning.com"
        target: "_blank"
      - name: "Audiobook shelf"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/audiobookshelf.svg"
        subtitle: "Audiobook server"
        url: "https://audiobookshelf.k8s.javydekoning.com/"
        target: "_blank"
      - name: "Metube"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/metube.svg"
        subtitle: "Youtube archiver"
        url: "https://ytdl.k8s.javydekoning.com"
        target: "_blank"
  - name: "Knowledge Management"
    icon: "fas fa-brain"
    items:
      - name: "OpenWebUI"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/open-webui.svg"
        subtitle: "AI Chat Interface"
        url: "https://openwebui.k8s.javydekoning.com"
        target: "_blank"
      - name: "LiteLLM"
        logo: "https://phoenix.arize.com/wp-content/uploads/2025/03/litellm.png"
        subtitle: "LLM & MCP Gateway"
        url: "https://litellm.k8s.javydekoning.com"
        target: "_blank"
      - name: "n8n"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/n8n.svg"
        subtitle: "AI workflow automation"
        url: "https://n8n.k8s.javydekoning.com"
        target: "_blank"
      - name: "KaraKeep"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/karakeep.svg"
        subtitle: "Web archival"
        url: "https://karakeep.lab.javydekoning.com"
        target: "_blank"
      - name: "Librechat"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/librechat.svg"
        subtitle: "Web archival"
        url: "https://librechat.k8s.javydekoning.com"
        target: "_blank"
  - name: "Infra & GitOps"
    icon: "fas fa-cloud"
    items:
      - name: "Unifi"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/unifi.svg"
        subtitle: "Network things"
        url: "https://unifi.javydekoning.com/"
        target: "_blank"
      - name: "Truenas"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/truenas.svg"
        subtitle: "Storage"
        url: "https://nas.javydekoning.com/"
        target: "_blank"
      - name: "ArgoCD"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/argo-cd.svg"
        subtitle: "GitOps"
        url: "https://argocd.k8s.javydekoning.com/"
        target: "_blank"
      - name: "Kopia"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/kopia.svg"
        subtitle: "Backups to s3"
        url: "https://kopia.k8s.javydekoning.com"
        target: "_blank"
  - name: "Code & Auth"
    icon: "fas fa-network-wired"
    items:
      - name: "Code server"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/vscode.svg"
        subtitle: "Code server"
        url: "https://code-server.k8s.javydekoning.com"
      - name: "Pocket ID"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/pocket-id.svg"
        subtitle: "Authentication"
        url: "https://pocket-id.k8s.javydekoning.com"
        target: "_blank"
      - name: GitHub Repo
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/github.svg"
        subtitle: "Link to homelab repo"
        url: "https://github.com/javydekoning/homelab"
        target: "_blank"
      - name: "Qui"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/qui.svg"
        subtitle: "Manage Torrents"
        url: "https://qui.k8s.javydekoning.com"
        target: "_blank"
  - name: "Smart Home & IoT"
    icon: "fas fa-home"
    items:
      - name: "Home-Assistant"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/home-assistant.svg"
        subtitle: "Home automation"
        url: "https://hass.k8s.javydekoning.com"
        target: "_blank"
      - name: "Zigbee2MQTT"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/zigbee2mqtt.svg"
        subtitle: "Zigbee 2 MQTT Bridge"
        url: "https://z2m.k8s.javydekoning.com/"
        target: "_blank"
      - name: "Frigate"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/frigate.svg"
        subtitle: "Network Video Recorder"
        url: "https://frigate.k8s.javydekoning.com"
        target: "_blank"
      - name: "evcc"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/evcc.svg"
        subtitle: "Energy management"
        url: "https://evcc.k8s.javydekoning.com"
        target: "_blank"
      - name: "ChangeDetection.io"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/changedetection.svg"
        subtitle: "Track changes"
        url: "https://changedetection.k8s.javydekoning.com"
        target: "_blank"
  - name: "Monitoring & Observability"
    icon: "fas fa-chart-line"
    items:
      - name: "Grafana"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/grafana.svg"
        subtitle: "Dashboards"
        url: "https://grafana.k8s.javydekoning.com"
        target: "_blank"
      - name: "Prometheus"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/prometheus.svg"
        subtitle: "Metric collection"
        url: "https://prometheus.k8s.javydekoning.com"
        target: "_blank"
      - name: "Alert Manager"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/alertmanager.svg"
        subtitle: "Alerts & notifications"
        url: "https://alertmanager.k8s.javydekoning.com"
        target: "_blank"
      - name: "Gatus"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/gatus.svg"
        subtitle: "Status page"
        url: "https://gatus.k8s.javydekoning.com"
        target: "_blank"
      - name: "Netronome"
        logo: "https://github.com/homarr-labs/dashboard-icons/raw/main/png/netronome.png"
        subtitle: "Network monitoring"
        url: "https://netronome.k8s.javydekoning.com"
        target: "_blank"
      - name: "Scrutiny"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/scrutiny.svg"
        subtitle: "Disk monitoring"
        url: "http://nas.javydekoning.com:31054/web/dashboard"
        target: "_blank"
  - name: "Media Request Management"
    icon: "fas fa-play"
    items:
      - name: "Sonarr"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/sonarr.svg"
        subtitle: "TV Shows"
        url: "https://sonarr.k8s.javydekoning.com"
        target: "_blank"
      - name: "Sonarr 1080p"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/sonarr.svg"
        subtitle: "TV Shows"
        url: "https://sonarr-1080.k8s.javydekoning.com"
        target: "_blank"
      - name: "Radarr"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/radarr.svg"
        subtitle: "Movies"
        url: "https://radarr.k8s.javydekoning.com"
        target: "_blank"
      - name: "Radarr 1080p"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/radarr.svg"
        subtitle: "Movies"
        url: "https://radarr-1080.k8s.javydekoning.com"
        target: "_blank"
      - name: "Seerr"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/overseerr.svg"
        subtitle: "Media request management"
        url: "https://jellyseerr.k8s.javydekoning.com"
        target: "_blank"
  - name: "DVR, Subtitle & Indexer Mgmt"
    icon: "fas fa-play"
    items:
      - name: "Autobrr"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/autobrr.svg"
        subtitle: "IRC Snatch bot"
        url: "https://autobrr.k8s.javydekoning.com"
        target: "_blank"
      - name: "Bazarr"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/bazarr.svg"
        subtitle: "Subtitle management"
        url: "https://bazarr.k8s.javydekoning.com"
        target: "_blank"
      - name: "Bazarr 1080p"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/bazarr.svg"
        subtitle: "Subtitle management"
        url: "https://bazarr-1080.k8s.javydekoning.com"
        target: "_blank"
      - name: "Prowlarr"
        logo: "https://raw.githubusercontent.com/homarr-labs/dashboard-icons/main/svg/prowlarr.svg"
        subtitle: "indexer manager"
        url: "https://prowlarr.k8s.javydekoning.com"
        target: "_blank"
