apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-assistant

helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    version: 0.3.44
    releaseName: home-assistant
    namespace: home-assistant
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - ns.yaml
  - volume.yaml
