apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smarthome

helmCharts:
  - name: home-assistant
    repo: http://pajikos.github.io/home-assistant-helm-chart/
    version: 0.3.41
    releaseName: home-assistant
    namespace: smarthome
    valuesFile: values.yaml
    includeCRDs: true

resources:
  - volume.yaml
