apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-qui
  labels:
    app: qbittorrent-qui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-qui
  template:
    metadata:
      labels:
        app: qbittorrent-qui
    spec:
      containers:
        - name: qui
          envFrom:
            - secretRef:
                name: qui
          image: ghcr.io/autobrr/qui:latest@sha256:cea707c0254b3afbce24a91350d771123ad769b4e66b30b7e651c78f0b350951
          ports:
            - containerPort: 7476
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: config-toml
              mountPath: /config/config.toml
              subPath: config.toml
      volumes:
        - name: config-volume
          hostPath:
            path: /config/qui
            type: DirectoryOrCreate
        - name: config-toml
          configMap:
            name: qbittorrent-qui-config
