apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent-qui
  labels:
    app: qbittorrent-qui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qbittorrent-qui
  template:
    metadata:
      labels:
        app: qbittorrent-qui
    spec:
      containers:
        - name: qui
          envFrom:
            - secretRef:
                name: qui
          image: ghcr.io/autobrr/qui:latest@sha256:5c7c08d5e8d4c4fe966106b58d3705f19921a69606b3dc4f237009a6c25a0ac7
          ports:
            - containerPort: 7476
              name: http
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: config-toml
              mountPath: /config/config.toml
              subPath: config.toml
      volumes:
        - name: config-volume
          hostPath:
            path: /config/qui
            type: DirectoryOrCreate
        - name: config-toml
          configMap:
            name: qbittorrent-qui-config
