apiVersion: apps/v1
kind: Deployment
metadata:
  name: mcp-inspector
  namespace: mcp-inspector
  labels:
    app: mcp-inspector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mcp-inspector
  template:
    metadata:
      labels:
        app: mcp-inspector
    spec:
      containers:
        - name: mcp-inspector
          image: ghcr.io/modelcontextprotocol/inspector:latest@sha256:7f7f39624a2f02c53ac5707e8e3f6a7d1e25e3b84769ad55b8b82f4392cf4f3d
          ports:
            - containerPort: 6274
              name: client
            - containerPort: 6277
              name: server
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "6274"
            - name: DANGEROUSLY_OMIT_AUTH
              value: "true"
