apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent-deployment
  namespace: dvr
  labels:
    app: rutorrent
    argocd.argoproj.io/instance: rutorrent
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rutorrent
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      containers:
        - name: rutorrent
          envFrom:
            - configMapRef:
                name: rutorrent-envs
          image: ghcr.io/crazy-max/rtorrent-rutorrent:latest@sha256:0e45cd71bcb3797d8cae1a5e2582641f5718f035e5d657539e7aca7fa7061b25
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - /usr/local/bin/healthcheck
            initialDelaySeconds: 600
            periodSeconds: 15
            timeoutSeconds: 10
            failureThreshold: 3
          ports:
            - name: http
              containerPort: 8080
            - name: xmlrpc
              containerPort: 8000
            - name: rtorrent
              containerPort: 51413
            - name: dht
              containerPort: 6881
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: config
              mountPath: /data
              subPath: rtorrent-config
            - name: temporary-rundir
              mountPath: /var/run/rtorrent
        - name: flood
          image: jesec/flood:latest@sha256:4b92628572d0b4ff740ca2d1e0262cf8e368cd39aa9e693a6dc2f681d71aadd2
          args: ["--allowedpath", "/data", "--allowedpath", "/var/run/rtorrent"]
          securityContext:
            runAsUser: 911
            runAsGroup: 911
          envFrom:
            - configMapRef:
                name: flood-envs
          ports:
            - containerPort: 3000
              name: http-flood
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /data
              subPath: rtorrent-config
            - name: temporary-rundir
              mountPath: /var/run/rtorrent
      volumes:
        - name: downloads
          hostPath:
            path: /downloads
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /config
            type: DirectoryOrCreate
        - name: temporary-rundir
          emptyDir: {}
