name: node-feature-discovery
apiVersion: v2
version: 1.0.0
dependencies:
  # Operator installs CRDs
  - name: node-feature-discovery
    version: 0.16.6
    repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
