name: intel-device-plugins
apiVersion: v2
version: 1.0.0
dependencies:
  # Operator installs CRDs
  - name: intel-device-plugins-operator
    version: 0.32.1
    repository: https://intel.github.io/helm-charts/
  - name: intel-device-plugins-gpu
    version: 0.32.0
    repository: https://intel.github.io/helm-charts/
