apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

helmCharts:
  - name: alloy
    repo: https://grafana.github.io/helm-charts
    version: 1.5.3
    releaseName: alloy
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true

configMapGenerator:
  - name: alloy-config
    options:
      disableNameSuffixHash: true
    files:
      - config.alloy=./config.alloy
