kind: ConfigMap
metadata:
  labels:
    app: homer
  name: homer-config
  namespace: default
apiVersion: v1
data:
  config.yml: |-
    # Homepage configuration
    # See https://fontawesome.com/v5/search for icons options

    title: "Homelab app dashboard"
    subtitle: "Running on k3s!"
    logo: "logo.png"
    icon: fas fa-server" # Optional icon

    header: true
    footer: false
    columns: auto

    links:
      - name: "Github
        icon: "fas fa-book"
        url: "https://github.com/javydekoning/homelab"

    defaults:
      layout: columns # Either 'columns', or 'list'
      colorTheme: auto # One of 'auto', 'light', or 'dark'

    # Services
    # First level array represent a group.
    # Leave only a "items" key if not using group (group name, icon &
    # tagstyle are optional, section separation will not be displayed).
    services:
      - name: "Media"
        icon: "fas fa-play"
        items:
          - name: "Jellyfin"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/jellyfin.png"
            subtitle: "Media"
            url: "https://jellyfin.k8s.javydekoning.com"
            target: "_blank"
          - name: "Plex"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/plex.png"
            subtitle: "Media"
            url: "https://plex.k8s.javydekoning.com"
            target: "_blank"
          - name: "Youtube-DL"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/youtubedl.png"
            subtitle: "Youtube downloader"
            url: "https://ytdl.k8s.javydekoning.com"
            target: "_blank"
          - name: "Autobrr"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/autobrr.png"
            subtitle: "Autodl replacement"
            url: "https://autobrr.k8s.javydekoning.com"
            target: "_blank"
          - name: "Sonarr"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/sonarr.png"
            subtitle: "TV Shows"
            url: "https://sonarr.k8s.javydekoning.com"
            target: "_blank"
          - name: "Radarr"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/radarr.png"
            subtitle: "Movies"
            url: "https://radarr.k8s.javydekoning.com"
            target: "_blank"
          - name: "Bazarr"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/bazarr.png"
            subtitle: "Subtitle management"
            url: "https://bazarr.k8s.javydekoning.com"
            target: "_blank"
          - name: "Prowlarr"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/prowlarr.png"
            subtitle: "indexer manager"
            url: "https://prowlarr.k8s.javydekoning.com"
            target: "_blank"
          - name: "Overseerr"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/overseerr.png"
            subtitle: "Media request management"
            url: "https://overseerr.k8s.javydekoning.com"
            target: "_blank"
          - name: "Tautulli"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/tautulli.png"
            subtitle: "Plex monitoring app"
            url: "https://tautulli.k8s.javydekoning.com/"
            target: "_blank"
          - name: "Audiobook shelf"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/audiobookshelf.png"
            subtitle: "Self-hosted audiobook and podcast server"
            url: "https://audiobookshelf.k8s.javydekoning.com/"
            target: "_blank"
      - name: "Management"
        icon: "fas fa-cloud"
        items:
          - name: "Kopia"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/kopia.png"
            subtitle: "Backups to s3"
            url: "https://kopia.k8s.javydekoning.com"
            target: "_blank"
          - name: "Unifi"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/unifi.png"
            subtitle: "Network things"
            url: "https://unifi.javydekoning.com/"
            target: "_blank"
          - name: "Truenas"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/truenas.png"
            subtitle: "Storage"
            url: "https://nas.javydekoning.com/"
            target: "_blank"
          - name: "ArgoCD"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/argocd.png"
            subtitle: "GitOps"
            url: "https://argocd.k8s.javydekoning.com/"
            target: "_blank"
          - name: GitHub Repo
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/github.png"
            subtitle: "Link to homelab repo"
            url: "https://github.com/javydekoning/homelab"
            target: "_blank"
          - name: "ruTorrent"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/rutorrent.png"
            subtitle: "Manage Torrents"
            url: "https://rutorrent.k8s.javydekoning.com"
            target: "_blank"
      - name: "Monitoring and automation"
        icon: "fas fa-download"
        items:
          - name: "evcc"
            logo: "https://github.com/walkxcode/dashboard-icons/raw/main/png/lnbits.png"
            subtitle: "Electric Vehicle (EV) charging control"
            url: "https://evcc.k8s.javydekoning.com"
            target: "_blank"
          - name: "Smokeping"
            logo: "https://github.com/walkxcode/dashboard-icons/raw/main/png/smokeping.png"
            subtitle: "Network monitoring"
            url: "https://smokeping.k8s.javydekoning.com"
            target: "_blank"
          - name: "Zigbee2MQTT"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/zigbee2mqtt.png"
            subtitle: "Zigbee 2 MQTT Bridge"
            url: "https://z2m.k8s.javydekoning.com/"
            target: "_blank"
          - name: "Home-Assistant"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/home-assistant.png"
            subtitle: "Home automation and monitoring"
            url: "https://hass.k8s.javydekoning.com"
            target: "_blank"
          - name: "Grafana"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/grafana.png"
            subtitle: "Monitoring dashboards"
            url: "https://grafana.k8s.javydekoning.com"
            target: "_blank"
          - name: "Prometheus"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/prometheus.png"
            subtitle: "Prometheus metric collection"
            url: "https://prometheus.k8s.javydekoning.com"
            target: "_blank"
          - name: "Alert Manager"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/alertmanager.png"
            subtitle: "Monitoring alerts"
            url: "https://alertmanager.k8s.javydekoning.com"
            target: "_blank"
          - name: "Frigate"
            logo: "https://github.com/walkxcode/dashboard-icons/raw/main/png/frigate.png"
            subtitle: "Network Video Recorder"
            url: "https://frigate.k8s.javydekoning.com"
            target: "_blank"
          - name: "OpenSpeedtest"
            logo: "https://github.com/walkxcode/dashboard-icons/raw/main/png/openspeedtest.png"
            subtitle: "Local Speedtest"
            url: "https://openspeedtest.k8s.javydekoning.com"
            target: "_blank"
          - name: "Gatus"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/gatus.png"
            subtitle: "Status page"
            url: "https://gatus.k8s.javydekoning.com"
            target: "_blank"
          - name: "ChangeDetection.io"
            logo: "https://raw.githubusercontent.com/walkxcode/dashboard-icons/main/png/changedetection-io.png"
            subtitle: "Detect website content changes and perform meaningful action"
            url: "https://changedetection.k8s.javydekoning.com"
            target: "_blank"
