apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dvr

resources:
  - ../../base/
  - ./ingress-ext.yaml

images:
  - name: app
    newName: ghcr.io/seerr-team/seerr
    newTag: latest

configMapGenerator:
  - name: env-configmap
    literals:
      - TZ=Europe/Amsterdam
      - LOG_LEVEL=debug

namePrefix: seerr-

labels:
  - includeSelectors: true
    pairs:
      app: seerr

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: ingress-patch.yaml
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: seerr
    target:
      kind: Deployment
      name: deployment
