apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-netronome-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager
  target:
    name: netronome-credentials-env
  dataFrom:
    - extract:
        key: k8s-homelab-secrets
        property: netronome

