apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - deployment.yaml
  - external-secret.yaml
  - ingress.yaml
  - service.yaml
configMapGenerator:
  - name: netronome-config
    files:
      - config.toml

