apiVersion: apps/v1
kind: Deployment
metadata:
  name: evcc
  labels:
    app: evcc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evcc
  template:
    metadata:
      labels:
        app: evcc
    spec:
      containers:
        - name: evcc
          image: evcc/evcc:latest@sha256:c722758d8ea9fb1f677c577b5a82c55117e89f2022dab2cd26f93e597cb9ba00
          command:
            - evcc
          ports:
            - containerPort: 7070
              name: http
            - containerPort: 8887
              name: udp
              protocol: UDP
          volumeMounts:
            - name: config
              mountPath: /etc/evcc.yaml
              subPath: evcc.yaml
            - name: data
              mountPath: /root/.evcc
      volumes:
        - name: config
          configMap:
            name: evcc-config
        - name: data
          hostPath:
            path: /config/evcc
            type: DirectoryOrCreate
