apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: evcc

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configmapGenerator:
  - name: evcc-config
    files:
      - evcc.yaml
