apiVersion: v1
kind: Service
metadata:
  name: evcc
  labels:
    app: evcc
spec:
  type: ClusterIP
  ports:
    - port: 7070
      targetPort: 7070
      protocol: TCP
      name: http
    - port: 8887
      targetPort: 8887
      protocol: UDP
      name: udp
  selector:
    app: evcc
