apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat
  labels:
    app.kubernetes.io/name: librechat
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: librechat

  template:
    metadata:
      labels:
        app.kubernetes.io/name: librechat
    spec:
      serviceAccountName: librechat
      securityContext:
        fsGroup: 2000
      containers:
        - name: librechat
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            runAsUser: 1000
          image: ghcr.io/danny-avila/librechat:latest@sha256:0683d43fb72342d253d82785625c752e06403d53053c20e272b8865ea6d38092
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 3080
          readinessProbe:
            httpGet:
              path: /health
              port: 3080
          envFrom:
            - configMapRef:
                name: librechat-envs
            - secretRef:
                name: librechat-credentials-env
          volumeMounts:
            - name: librechat-config-volume
              mountPath: /app/librechat.yaml
              subPath: librechat.yaml
              readOnly: true
            - name: librechat-images
              mountPath: /app/client/public/images
      volumes:
        - name: librechat-config-volume
          configMap:
            name: librechat-config
        - name: librechat-images
          hostPath:
            path: /config/librechat
            type: DirectoryOrCreate
