apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: librechat
  labels:
    app.kubernetes.io/name: librechat
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - "librechat.k8s.javydekoning.com"
  rules:
    - host: "librechat.k8s.javydekoning.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: librechat
                port:
                  number: 3080
