apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui-ingress
  namespace: openwebui
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - openwebui.k8s.javydekoning.com
      secretName: javydekoning-com-tls
  rules:
    - host: openwebui.k8s.javydekoning.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openwebui
                port:
                  name: http
