apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: smokeping-ingress
  namespace: monitoring
  labels:
    app: smokeping
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - smokeping.k8s.javydekoning.com
  rules:
    - host: smokeping.k8s.javydekoning.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: smokeping
                port:
                  name: http
