apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: intel-device-plugins

helmCharts:
  - name: intel-device-plugins-gpu
    repo: https://intel.github.io/helm-charts/
    version: 0.34.1
    releaseName: intel-device-plugins-gpu
    namespace: intel-device-plugins
    valuesFile: values.yaml
    includeCRDs: true
